name: Maven Build & Allure Report CI

on:
  push:
    branches:
      - main 

jobs:
  build_and_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for deploying to gh-pages
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for report history feature

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Tests and Generate Allure Results
      run: mvn clean test

    # New step using the stable 'andgineer' action
    - name: Generate Allure test report
      uses: andgineer/allure-report@v3.6 
      if: always()
      id: allure-report-step
      env:
          JAVA_HOME: ""
      with:
        allure-results: target/allure-results # Your folder in the root directory
        # We specify where to build the report temporarily before deployment
        reports-site-path: allure-report-site 
